-- Auto-extracted colour from each product name. Run once in Supabase SQL editor.
UPDATE products SET colors = ARRAY['Black'] WHERE slug = 'dell-lattitude-5540-210-bgbj-i5-black' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Natural Silver'] WHERE slug = 'hp-15-fd0133wm-natural-silver' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Silver'] WHERE slug = 'hp-15-fd0250wm-silver' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Silver'] WHERE slug = 'hp-250-g10-silver' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Natural Silver'] WHERE slug = 'hp-ai-15-fd2023ne-natural-silver' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Silver'] WHERE slug = 'hp-15-fd1899nr-silver' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Natural Silver'] WHERE slug = 'hp-15-fd0143ne-natural-silver' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Natural Silver'] WHERE slug = 'hp-15-fd0371nia-natural-silver' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Natural Silver'] WHERE slug = 'hp-15-fd0138ne-natural-silver' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Natural Silver'] WHERE slug = 'hp-15-fd0142ne-natural-silver' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Naturalsilver'] WHERE slug = 'hp-ai-15-fd2022ne-naturalsilver' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Blue'] WHERE slug = 'hp-elitebook-ultra-g1q-a4je4ut-aba-blue' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Silver'] WHERE slug = 'hp-elitebook-660g11-a6uc4ut-aba-silver' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Silver'] WHERE slug = 'hp-elitebook-840g11-b1sb9up-silver' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Nightfall Black'] WHERE slug = 'hp-spectre-16-aa0013-nightfall-black-refurb' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Meteor Silver'] WHERE slug = 'hp-envy-16-ad0097nr-meteor-silver-refurb' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Mica Silver'] WHERE slug = 'hp-victus-15-fa2082wm-mica-silver' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Mica Silver'] WHERE slug = 'hp-victus-15-fa2021nia-mica-silver' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Shadow Black'] WHERE slug = 'hp-omen-16-an0075cl-shadow-black' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Arctic Grey'] WHERE slug = 'lenovo-ip1-82lx00gsad-arctic-grey-carry-case' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Arctic Grey'] WHERE slug = 'lenovo-ips3-82x700hrax-arctic-grey' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Arctic Grey'] WHERE slug = 'lenovo-ips3-82x700dfdp-arctic-grey-carry-case' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Business Black'] WHERE slug = 'lenovo-v15-83gw0076gp-business-black' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Business Black'] WHERE slug = 'lenovo-v15-83gw0066pb-business-black' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Abyss Blue'] WHERE slug = 'lenovo-ip1-83b40006us-abyss-blue' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Abyss Blue'] WHERE slug = 'lenovo-ip1-83b40006us-512gb-abyss-blue' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Cloud Grey'] WHERE slug = 'lenovo-ip1-83b40008us-cloud-grey' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Cloud Grey'] WHERE slug = 'lenovo-ip1-83b40008us-512gb-cloud-grey' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Luna Grey'] WHERE slug = 'lenovo-ips3-83k100e9ax-luna-grey' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Luna Grey'] WHERE slug = 'lenovo-ips3-83k100c1dp-luna-grey' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Iron Grey'] WHERE slug = 'lenovo-v15-83cr000pin-iron-grey' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Business Black'] WHERE slug = 'lenovo-v14-83a000pcus-business-black' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Business Black'] WHERE slug = 'lenovo-v15-83gw006ved-business-black-carry-case' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Luna Grey'] WHERE slug = 'lenovo-v15-83hf00emig-luna-grey' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Luna Grey'] WHERE slug = 'lenovo-ideapad-slim3-83k100e8ax-luna-grey' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Luna Grey'] WHERE slug = 'lenovo-ideapad-slim3-83k100e7dp-luna-grey' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Luna Grey'] WHERE slug = 'lenovo-ideapad-slim3-82x700huus-luna-grey' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Arctic Grey'] WHERE slug = 'lenovo-thinkbook-16-21sk0030gq-arctic-grey-carry-case' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Storm Grey'] WHERE slug = 'lenovo-yoga-7-83dl0002us-storm-grey' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Luna Grey'] WHERE slug = 'lenovo-loq-83dv01bcax-luna-grey' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Luna Grey'] WHERE slug = 'lenovo-loq-83dv000eax-luna-grey' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Luna Grey'] WHERE slug = 'lenovo-loq-83lk003tps-luna-grey' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Luna Grey'] WHERE slug = 'lenovo-loq-83dv000dax-luna-grey' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Luna Grey'] WHERE slug = 'lenovo-loq-83je00kwax-luna-grey' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Luna Grey'] WHERE slug = 'lenovo-loq-83je0114ax-luna-grey' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Luna Grey'] WHERE slug = 'lenovo-loq-83je002lus-luna-grey' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Luna Grey'] WHERE slug = 'lenovo-loq-83je00xafu-512gb-luna-grey' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Luna Grey'] WHERE slug = 'lenovo-loq-83je00xafu-luna-grey' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Storm Grey'] WHERE slug = 'lenovo-legion-5-83nx0000us-storm-grey' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Eclipse Black'] WHERE slug = 'lenovo-legion-5-83ly00n9ax-eclipse-black' AND (colors IS NULL OR colors = '{}'::text[]);
UPDATE products SET colors = ARRAY['Eclipse Black'] WHERE slug = 'lenovo-legion-pro-5-83nn001xax-eclipse-black' AND (colors IS NULL OR colors = '{}'::text[]);
